language: ruby
rvm:
  - 2.2
env: 
  - RAILS_ENV=test
before_script:
  - "mysql -e 'create database quiznoob_test;'"
  - "cp ./.travis.database.yml ./config/database.yml"
script: 
  - bundle exec rake db:schema:load
  - bundle exec rake db:test:prepare
  - bundle exec rake spec
